# Generated by Django 3.1.7 on 2021-06-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdapp', '0002_auto_20210628_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='chead0',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='head0',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='thumbnail',
            new_name='video',
        ),
    ]
